name: "Homebox"
description: "Run Homebox, the home inventory and organization system"
url: "https://github.com/sysadminsmedia/homebox"
slug: "homebox"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
startup: application
webui: "[PROTO:option_name]://[HOST]:[PORT:7745]"
boot: auto
ports:
  7745/tcp: 7745
version: 0.26.2
host_network: false
apparmor: true
